### ISSUE TITLE
Render mermaid charts as static SVGs?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/ecosystem-platform#27]
I noticed we added mermaid chart support for issue #10 using an external JS lib from a CDN to render client-side. It might be an interesting improvement to render these at build-time as static SVGs with something like mermaid CLI (or whatever can integrate with the doc generation tool):

https://github.com/mermaidjs/mermaid.cli

**Comment by NoWorries** [comment]
The SVG rendering has been hit and miss in my recent tests, might not be as predictable.
Text boxes in the SVG are not extending and clip the content:

![image](https://user-images.githubusercontent.com/803064/68351486-7cc91180-0168-11ea-98aa-de1d3f3a5024.png)

Rendering in page was always great though:

![image](https://user-images.githubusercontent.com/803064/68351507-910d0e80-0168-11ea-8704-665ec8d01442.png)

**Comment by lmorchard** [comment]
> The SVG rendering has been hit and miss in my recent tests

Ah, crud. Well, that's worth knowing. I figured it would be nice to have one fewer external JS dependency in the generated docs, but they're not *broken* right now

**Comment by NoWorries** [comment]
It looks like it is just the font-size in the exported SVG is larger. Perhaps if that was addressed it would work better, but more of a bug with mermaid i guess? Or at least the mermaid-live-editor i used

**Comment by clouserw** [comment]
Yeah, this is working fine, I'm going to close this.  :v:
