### ISSUE TITLE
Stuff Shane would like to write

### ISSUE THREAD

**Issue by johngruen** [mozilla/ecosystem-platform#29]
APPENDIX: Stuff SHANE would like to write

Overall architecture of services
How content server fits together
Extend Les’ Testing Doc
Difference between Authentication and Authorization (General)
Expand out Relying Party Checklist

https://docs.google.com/document/d/14P94X3RnVb1SyatOp2H_NOPlj2jIvxrTDsusSOxK2zQ/edit

**Comment by clouserw** [comment]
I think this is all incorporated into the new docusaurus docs
