### ISSUE TITLE
Commit rights for this repo?

### ISSUE THREAD

**Issue by rfk** [mozilla/ecosystem-platform#3]
I was surprised to find that I don't have the ability to push to branches in this repo. @johngruen what's the intended security model for this, should we add some teams with admin privileges?

**Comment by johngruen** [comment]
no, let's fix that

**Comment by rfk** [comment]
@johngruen I assume you have access as the creator of the repo, please add the [fxa-devs](https://github.com/orgs/mozilla/teams/fxa-devs) and [sync-devs](https://github.com/orgs/mozilla/teams/sync-devs) teams with admin privileges.

**Comment by linacambridge** [comment]
Done! FxA, Sync, and a-s should have admin access to this repo now.
